export default interface Appointment {
    fechaCreacionTurnoUTC: string,
    fechaTurnoUTC: string,
    email: string,
    servicio: string,
    prestador: string,
    ubicacion: string,
    observaciones: string,
    estado: string,
    id: string, // auto-generated by us as an internal id.
    turnoId?: number // generated by DASPU's backend when the appointment is Confirmed (from Pending to Confirmed)
}